#!/bin/bash

echo "🎯 Capacinator Commands"
echo "======================="
echo ""
echo "📋 DEVELOPMENT:"
echo "  npm run dev             - Start development servers in background"
echo "  npm run dev:stop        - Stop development servers"
echo "  npm run dev:logs        - View live development logs"
echo "  npm run dev:no-bg       - Start development servers (blocking)"
echo "  npm run dev:server      - Start development server only"
echo "  npm run dev:client      - Start development client only"
echo "  npm run dev:electron    - Start development electron app"
echo ""
echo "🏭 PRODUCTION:"
echo "  npm run prod:start         - Start production server in background"
echo "  npm run prod:stop          - Stop production server"
echo "  npm run prod:logs          - View live production logs"
echo "  npm run prod:frontend:start - Start production frontend in background"
echo "  npm run prod:frontend:stop  - Stop production frontend"
echo "  npm run prod:frontend:logs  - View live frontend logs"
echo ""
echo "🖥️  SERVER ONLY:"
echo "  npm run server:start - Start compiled server in background"
echo "  npm run server:stop  - Stop server"
echo "  npm run server:logs  - View live server logs"
echo ""
echo "🧪 E2E TESTING:"
echo "  npm run e2e:start        - Start E2E servers in background"
echo "  npm run e2e:stop         - Stop E2E servers"
echo "  npm run e2e:stop:cleanup - Stop E2E servers and cleanup database"
echo "  npm run e2e:reset        - Reset E2E environment"
echo "  npm run e2e:logs         - View live E2E logs"
echo ""
echo "🔨 BUILD & DISTRIBUTION:"
echo "  npm run build        - Build all components"
echo "  npm run build:server - Build server only"
echo "  npm run build:client - Build client only"
echo "  npm run build:electron - Build electron app"
echo "  npm run dist         - Build and create distributables"
echo "  npm run dist:win     - Build and create Windows distribution"
echo "  npm run dist:mac     - Build and create macOS distribution"
echo "  npm run dist:linux   - Build and create Linux distribution"
echo ""
echo "🧪 TESTING:"
echo "  npm run test                    - Run all tests"
echo "  npm run test:client            - Run client tests (watch mode)"
echo "  npm run test:client:run        - Run client tests (single run)"
echo "  npm run test:server            - Run server tests"
echo "  npm run test:unit              - Run all unit tests"
echo "  npm run test:e2e               - Run E2E tests"
echo "  npm run test:e2e:ui            - Run E2E tests with UI"
echo "  npm run test:e2e:headed        - Run E2E tests in headed mode"
echo "  npm run test:e2e:isolated      - Run isolated E2E tests"
echo "  npm run test:e2e:isolated:ui   - Run isolated E2E tests with UI"
echo "  npm run test:e2e:isolated:headed - Run isolated E2E tests in headed mode"
echo "  npm run test:e2e:isolated:debug - Run isolated E2E tests in debug mode"
echo "  npm run test:e2e:comprehensive - Run comprehensive E2E scenarios"
echo "  npm run test:e2e:enterprise    - Run enterprise E2E scenario"
echo "  npm run test:e2e:agile         - Run agile E2E scenario"
echo "  npm run test:e2e:consulting    - Run consulting E2E scenario"
echo "  npm run test:scenarios         - Run scenario tests"
echo "  npm run test:scenarios:unit    - Run scenario unit tests"
echo "  npm run test:scenarios:e2e     - Run scenario E2E tests"
echo "  npm run test:scenarios:corruption - Run scenario corruption tests"
echo "  npm run test:scenarios:all     - Run all scenario tests"
echo ""
echo "🔍 CODE QUALITY:"
echo "  npm run lint      - Run ESLint"
echo "  npm run typecheck - Run TypeScript type checking"
echo ""
echo "🗄️  DATABASE:"
echo "  npm run db:init         - Initialize database"
echo "  npm run db:migrate      - Run database migrations"
echo "  npm run db:migrate-data - Run data migrations"
echo "  npm run db:seed         - Seed database with test data"
echo ""
echo "📊 IMPORT/EXPORT:"
echo "  npm run import:excel      - Import Excel data"
echo "  npm run import:excel:help - Show Excel import help"
echo ""
echo "🖥️  ELECTRON:"
echo "  npm run start - Start electron app"
echo ""
echo "💡 Commands with :start/:stop/:logs are non-blocking and run in background"
echo "   Use the :stop commands to gracefully shut down services"
echo "   Use the :logs commands to monitor running services"