#!/bin/bash

echo "🎯 Capacinator Non-Blocking Commands"
echo "======================================"
echo ""
echo "📋 DEVELOPMENT:"
echo "  npm run dev        - Start development servers in background"
echo "  npm run dev:stop   - Stop development servers"
echo "  npm run dev:logs   - View live development logs"
echo ""
echo "🏭 PRODUCTION:"
echo "  npm run prod:start         - Start production server in background"
echo "  npm run prod:stop          - Stop production server"
echo "  npm run prod:logs          - View live production logs"
echo "  npm run prod:frontend:start - Start production frontend in background"
echo "  npm run prod:frontend:stop  - Stop production frontend"
echo "  npm run prod:frontend:logs  - View live frontend logs"
echo ""
echo "🖥️  SERVER ONLY:"
echo "  npm run server:start - Start compiled server in background"
echo "  npm run server:stop  - Stop server"
echo "  npm run server:logs  - View live server logs"
echo ""
echo "🧪 E2E TESTING:"
echo "  npm run e2e:start        - Start E2E servers in background"
echo "  npm run e2e:stop         - Stop E2E servers"
echo "  npm run e2e:stop:cleanup - Stop E2E servers and cleanup database"
echo "  npm run e2e:reset        - Reset E2E environment"
echo "  npm run e2e:logs         - View live E2E logs"
echo ""
echo "📝 LEGACY (BLOCKING - use alternatives above):"
echo "  npm run start:prod         - [BLOCKING] Use prod:start instead"
echo "  npm run start:prod:frontend - [BLOCKING] Use prod:frontend:start instead"
echo "  npm run start:server       - [BLOCKING] Use server:start instead"
echo ""
echo "💡 All commands are non-blocking and run in background"
echo "   Use the :stop commands to gracefully shut down services"
echo "   Use the :logs commands to monitor running services"